const data = [
    {
        question: "Who painted the Mona Lisa??",
        a: "Vincent van Gogh",
        b: "Papblo Picasso",
        c: "Leonardo da Vinci",
        d: "Michelangelo",
        correct: "c",
    },
    {
        question: "What is the capital of France?",
        a: "Paris",
        b: "Monaco",
        c: "Marseille",
        d: "Nice",
        correct: "a",
    },
    {
        question: "What is the tallest mountain in the world?",
        a: "K2",
        b: "Mount Everest",
        c: "Makalu",
        d: "Lhotse",
        correct: "b",
    },
    {
        question: "What is the largest planet in our solar system?",
        a: "Saturn",
        b: "Uranus",
        c: "Neptune",
        d: "Jupiter",
        correct: "d",
    },
    {
        question: "Who wrote the play Romeo and Juliet?",
        a: "J.R.R. Tolkien",
        b: "Charles Dickens",
        c: "Lev Tolstoj",
        d: "William Shakespeare",
        correct: "d",
    },
    {
        question: "What is the capital city of Australia?",
        a: "Perth",
        b: "Canberra",
        c: "Melbourne",
        d: "Sydney",
        correct: "b",
    },
    {
        question: "What is the primary language spoken in Brazil?",
        a: "French",
        b: "Spanish",
        c: "Portuguese",
        d: "English",
        correct: "c"
    },
    {
        question: "Who is known as the inventor of the lightbulb?",
        a: "Thomas Edison",
        b: "Nikola Tesla",
        c: "Alexander Graham Bell",
        d: "Albert Einstein",
        correct: "a",
    },
    {
        question: "What is the largest ocean on Earth?",
        a: "Indian",
        b: "Atlantic",
        c: "Pacific",
        d: "Arctic",
        correct: "c",
    },

];